### ISSUE TITLE
Got an class not found error-javax.servlet.http.HttpSessionIdListener

### ISSUE THREAD

**Issue by gonedays** [taodongl/example_executable_war_with_jetty#1]
Hi, I cloned your project, and got an WAR, and the javax.\* and jetty classes did included in the WAR, but when I run with "java -jar -Dport=10080 jettyExam.war", I get exception as below.
I am using maven 3.2.3, JDK 1.8.  JETTY 9.2.10.v20150310. And I have modified the maven JDk compiler as JDK1.8 in pom.xml file.  Seems need to add some other dependency in POM file.

---

E:\java\JEEworkspace\example_executable_war_with_jetty\jettyExam\target>java -ja
r -Dport=10080 jettyExam.war
2015-03-15 12:29:07.765:INFO::main: Logging initialized @185ms
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/http/Ht
tpSessionIdListener
        at org.eclipse.jetty.server.session.SessionHandler.<clinit>(SessionHandl
er.java:54)
        at org.eclipse.jetty.servlet.ServletContextHandler.newSessionHandler(Ser
vletContextHandler.java:241)
        at org.eclipse.jetty.servlet.ServletContextHandler.getSessionHandler(Ser
vletContextHandler.java:334)
        at org.eclipse.jetty.servlet.ServletContextHandler.relinkHandlers(Servle
tContextHandler.java:180)
        at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContext
Handler.java:157)
        at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:253)

```
    at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:201)

    at Runner.main(Runner.java:16)
```

Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpSessionIdLis
tener
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more

**Comment by gonedays** [comment]
it was dependency conflict in pom file.  resolved it.
